name: Docker Image CI

on:
  create:
    tags:
      - V*

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        repository: covidgraph/data-cord19
        tags: latest
        username: ${{ secrets.DZD_DOCKER_USERNAME }}
        password: ${{ secrets.DZD_DOCKER_PASSWORD }}
